server:
 port: 8080

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/kino-search
  username: postgres
  password: root
 freemarker.expose-request-attributes: true

 jpa:
  show-sql: false
  hibernate.ddl-auto: validate
  generate-ddl: false
  open-in-view: true
  properties.hibernate:
   temp.use_jdbc_metadata_defaults: false
   jdbc.lob.non_contextual_creation: true
 session.jdbc:
  initialize-schema: always
  table-name: SPRING_SESSION